# Generated by Django 5.1.7 on 2025-05-11 20:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='news_images')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TypeProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VacancyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='vacancy_images')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to='product_images')),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('volume', models.TextField(max_length=100, null=True)),
                ('type_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_maf.typeproductmodel')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyPersonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('resume', models.FileField(upload_to='resume/', verbose_name='Резюме')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('position_text', models.CharField(blank=True, max_length=255)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_maf.vacancymodel')),
            ],
        ),
    ]
